/*

 DUNGEON.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : C:\Users\mike\Desktop\GBDEV\game\tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define dungeonWidth 32
#define dungeonHeight 18
#define dungeonBank 0

extern unsigned char dungeon[];

/* End of DUNGEON.H */
